LICENSE-3rdparty.csv

Update 3rd party csv

---

docs/attack-techniques/AWS/aws.execution.ec2-user-data.md
docs/attack-techniques/AWS/index.md
docs/attack-techniques/list.md
docs/user-guide/getting-started.md
internal/attacktechniques/aws/execution/ec2-user-data/main.go
internal/attacktechniques/aws/execution/ec2-user-data/main.tf
internal/attacktechniques/aws/execution/ec2-user-data/malicious-user-data.sh
internal/attacktechniques/main.go

Reference: https://hackingthe.cloud/aws/exploitation/local-priv-esc-mod-instance-att/
Sample output:
```
2022/02/01 12:45:10 Checking your authentication against the AWS API
2022/02/01 12:45:11 Stopping instance i-0fb8c40315bdf8b7e
2022/02/01 12:45:12 Waiting for instance to be stopped
2022/02/01 12:46:29 Injecting malicious user data
2022/02/01 12:46:31 Starting instance
2022/02/01 12:46:38 Instance i-0fb8c40315bdf8b7e started, malicious script in user data has been executed
```
Proof the "malicious script" in user data is executed:
```
$ aws ssm start-session --target i-0fb8c40315bdf8b7
Starting session with SessionId: christophe-05a5849858b1a716a
sh-4.2$ cat /tmp/id.txt
uid=0(root) gid=0(root) groups=0(root)
```

New attack technique: Execution using EC2 User Data (closes #78)

---

LICENSE-3rdparty.csv
Makefile

Add thirdyparty-licenses target

---

docs/attack-techniques/AWS/aws.discovery.ec2-download-user-data.md
docs/attack-techniques/kubernetes/index.md
docs/attack-techniques/kubernetes/k8s.privilege-escalation.privileged-pod.md
docs/attack-techniques/list.md
internal/attacktechniques/k8s/privilege-escalation/privileged-pod/main.go
internal/attacktechniques/k8s/privilege-escalation/privileged-pod/main.tf
internal/attacktechniques/main.go

New attack technique: Create privileged K8s pod (closes #92)

---

cmd/stratus/cleanup_cmd.go
cmd/stratus/detonate_cmd.go
cmd/stratus/main.go
cmd/stratus/revert_cmd.go
cmd/stratus/util.go
cmd/stratus/warmup_cmd.go
internal/utils/functions.go

This PR is an attempt at solving https://github.com/DataDog/stratus-red-team/issues/15 to run commands in parallel by using as many go routines as max available procs depending on the config.
I haven't been able to test it directly yet because I do not have an environment setup completely
https://github.com/DataDog/stratus-red-team/issues/15

Make commands run in parallel

---

docs/attack-techniques/kubernetes/index.md
docs/attack-techniques/kubernetes/k8s.credential-access.dump-secrets.md
docs/attack-techniques/list.md
internal/attacktechniques/k8s/credential-access/dump-secrets/main.go
internal/attacktechniques/main.go

Sample output:
```
2022/02/23 12:59:07 Checking your authentication against kubernetes
2022/02/23 12:59:08 Attempting to dump secrets in all namespaces
2022/02/23 12:59:08 Successfully dumped 40 secrets from the cluster
```
Essentially doing a `kubectl get secrets -A -o yaml`

New attack technique: Dump K8s cluster secrets

---

internal/attacktechniques/aws/credential-access/ec2-steal-instance-credentials/main.go

Fixes an issue where we would try to execute a command through AWS SSM before the instance gets registered.
Precompiled binary attached for testing if needed, but confirmed it works better from my side: https://drive.google.com/file/d/1sMeGjwIEZL-4e9UIR2GhJ3KAcRTdbzuj/view?usp=sharing

ec2-steal-instance-credentials: Ensure instance is registered in SSM (closes #108)

---

cmd/stratus/util.go
examples/custom/detonate_custom_technique.go
internal/providers/main.go
pkg/stratus/providers.go

See https://github.com/DataDog/stratus-red-team/issues/117

Bug fix: Provide an utility method to retrieve provider configuration in an non-internal package

---

docs/attack-techniques/AWS/aws.initial-access.console-login-without-mfa.md
docs/attack-techniques/AWS/index.md
docs/attack-techniques/list.md
internal/attacktechniques/aws/initial-access/console-login-without-mfa/main.go
internal/attacktechniques/aws/initial-access/console-login-without-mfa/main.tf
internal/attacktechniques/main.go
internal/providers/aws.go
internal/providers/kubernetes.go
internal/providers/main.go

Generated docs: 
Source: https://expel.com/blog/incident-report-from-cli-to-console-chasing-an-attacker-in-aws/
Sample output:

New TTP: AWS Console login without MFA

---

docs/attack-techniques/azure/azure.execution.vm-run-command.md
docs/attack-techniques/azure/index.md
docs/attack-techniques/list.md
docs/user-guide/getting-started.md
go.mod
go.sum
internal/attacktechniques/azure/execution/vm-run-command/main.go
internal/attacktechniques/azure/execution/vm-run-command/main.tf
internal/attacktechniques/main.go
pkg/stratus/platform.go
pkg/stratus/providers.go
tools/doc.tpl
tools/full-list.tpl
tools/generate-techniques-documentation.go
tools/index-by-platform.tpl

* New attack technique: Azure VM Run Command
* Related to !116

Add azure run command

---

docs/attack-techniques/azure/azure.execution.vm-custom-script-extension.md
docs/attack-techniques/azure/index.md
docs/attack-techniques/list.md
internal/attacktechniques/azure/execution/vm-custom-script-extension/main.go
internal/attacktechniques/azure/execution/vm-custom-script-extension/main.tf
internal/attacktechniques/main.go

* New attack technique: Azure Custom Script Extension
* Related to !116

Add azure custom script extension

---

docs/attack-techniques/GCP/gcp.persistence.create-service-account-key.md
docs/attack-techniques/GCP/index.md
docs/attack-techniques/list.md
docs/attack-techniques/supported-platforms.md
docs/user-guide/getting-started.md
v2/go.mod
v2/internal/attacktechniques/gcp/persistence/create-service-account-key/main.go
v2/internal/attacktechniques/gcp/persistence/create-service-account-key/main.tf
v2/internal/attacktechniques/main.go
v2/internal/providers/gcp.go
v2/pkg/stratus/platform.go
v2/pkg/stratus/providers.go
v2/pkg/stratus/registry_test.go
v2/tools/generate-techniques-documentation.go

* New attack technique
* Enhancement
Adds initial support for GCP techniques, and initial GCP Technique 
closes #53 #128 
Adds initial provider for GCP, and initial GCP Attack Technique.
Notes on initial GCP Provider:
- I decided against abstracting away client creation, as by default with the google cloud SDK, Application Default Credential flow will be used (see https://cloud.google.com/docs/authentication/production#automatically and https://pkg.go.dev/cloud.google.com/go#hdr-Authentication_and_Authorization for more details). Happy to refactor this instead to a factory that abstracts it away if it better matches the other provider patterns in the codebase.
- I verify auth by checking for the presence of a GCP project variable (the GCP TF Provider documentation has all possible ones …

Add initial support for GCP and first GCP technique 

---

docs/attack-techniques/GCP/gcp.persistence.create-admin-service-account.md
docs/attack-techniques/GCP/gcp.persistence.create-service-account-key.md
docs/attack-techniques/GCP/gcp.privilege-escalation.impersonate-service-accounts.md
docs/attack-techniques/GCP/index.md
docs/attack-techniques/list.md
docs/attack-techniques/supported-platforms.md
docs/user-guide/getting-started.md
v2/go.mod
v2/internal/attacktechniques/gcp/persistence/create-admin-service-account/main.go
v2/internal/attacktechniques/gcp/persistence/create-admin-service-account/main.tf
v2/internal/attacktechniques/gcp/persistence/create-service-account-key/main.go
v2/internal/attacktechniques/gcp/persistence/create-service-account-key/main.tf
v2/internal/attacktechniques/gcp/privilege-escalation/impersonate-service-accounts/main.go
v2/internal/attacktechniques/gcp/privilege-escalation/impersonate-service-accounts/main.tf
v2/internal/attacktechniques/main.go
v2/internal/providers/gcp.go
v2/internal/utils/functions.go
v2/pkg/stratus/platform.go
v2/pkg/stratus/providers.go
v2/pkg/stratus/registry_test.go
v2/pkg/stratus/runner/runner.go
v2/tools/generate-techniques-documentation.go

Aggregates #143, #154 and #155. Initial support for GCP to be released next week

Initial GCP support

---

v2/pkg/stratus/runner/runner.go
v2/pkg/stratus/runner/runner_test.go

Continue cleaning up when revert fails and --force is passed (closes #167)

---

docs/user-guide/usage.md

Fixed typo in usage.md, --clean-up should be --cleanup and added example command usage. Additionally, added a little more clarity in the main cleanup section. 
* What inspired you to submit this pull request?
We are avid users of Stratus and would like to contribute to new developments and improvements for the community.

nix-xin-usage-patch-1

---

.github/workflows/docker.yml
.github/workflows/docs.yml
.github/workflows/release.yml
.github/workflows/static-analysis.yml
.github/workflows/test.yml

Bumped to https://github.com/step-security/harden-runner/releases/tag/v1.5.0

CI hardening: egress traffic block mode

---

v2/internal/attacktechniques/aws/defense-evasion/organizations-leave/main.tf
v2/internal/attacktechniques/aws/discovery/ec2-get-user-data/main.tf
v2/internal/attacktechniques/aws/execution/ec2-launch-unusual-instances/main.tf

#224 introduced a few extra double quotes in some `main.tf` files. This PR fixes it.

Removed extra double quotes introduced by #224

---

v2/internal/attacktechniques/gcp/persistence/create-admin-service-account/main.tf

Fix GCP attack technique name length (closes #294)

---

v2/internal/attacktechniques/aws/persistence/rolesanywhere-create-trust-anchor/main.go

Fix max duration parameter of RolesAnywhere attack technique 

---

docs/comparison.md

https://github.com/awslabs/aws-cloudsaga

Add short comparison to Cloud Saga

---

v2/internal/attacktechniques/aws/credential-access/ec2-steal-instance-credentials/main.tf
v2/internal/attacktechniques/aws/discovery/ec2-enumerate-from-instance/main.tf
v2/internal/attacktechniques/aws/execution/ec2-launch-unusual-instances/main.tf
v2/internal/attacktechniques/aws/execution/ec2-user-data/main.tf
v2/internal/attacktechniques/aws/exfiltration/rds-share-snapshot/main.tf

Pin the version of the terraform-aws-vpc module used to avoid unresolvable constraints (closes #173)

---

docs/attack-techniques/GCP/gcp.exfiltration.share-compute-disk.md
docs/attack-techniques/GCP/index.md
docs/attack-techniques/list.md
docs/index.yaml
v2/internal/attacktechniques/gcp/exfiltration/share-compute-disk/main.go
v2/internal/attacktechniques/gcp/exfiltration/share-compute-disk/main.tf
v2/internal/attacktechniques/main.go

New GCP attack technique: Exfiltrating a GCP Compute Disk

---

docs/comparison.md

cc @KatTraxler @Cyb3rWard0g feedback welcome

Add comparison to DerF and Cloud Katana

---

Makefile

Enhancement: Improvements were made to the Makefile to allow for readability, consistency and adherence to best practices.
Reading through and understanding Makefiles, their importance and how to write them in a more readable manner following any related best practices that would enhance its maintainability.
N/A
Changes include:
* Utilizing variables for better code maintenance i.e. GOFLAGS & BIN_DIR
* Ensuring make targets are well-documented and self-explanatory
* Provided informative messaging during running targets
* Enabling use of GO modules with "GOMODULE=on"
* Using '@' to suppress unnecessary command echoing

Improve Makefile for better maintanability

---

.goreleaser.yaml

https://goreleaser.com/customization/homebrew/

Have GoReleaser send a PR for homebrew updates

---

v2/pkg/stratus/runner/runner.go
v2/pkg/stratus/runner/terraform.go

Allows for proper cancellation and timeouts mechanisms, especially on programmatic usage.

Allow specifying context when instantiating Stratus Red Team runners and propagate them down to Terraform

---

docs/attack-techniques/AWS/aws.discovery.ec2-download-user-data.md

Fixed Broke Link aws.discovery.ec2-download-user-data.md

---

Formula/stratus-red-team.rb

Brew formula update for stratus-red-team version v2.17.0

---

docs/attack-techniques/azure/azure.execution.vm-run-command.md
v2/internal/attacktechniques/azure/execution/vm-run-command/main.go

Adds documentation reference for technique.
Fixes #552

Add doc references

---

Formula/stratus-red-team.rb

Brew formula update for stratus-red-team version v2.18.0

---

Formula/stratus-red-team.rb

Brew formula update for stratus-red-team version v2.19.0

---

Formula/stratus-red-team.rb

Brew formula update for stratus-red-team version v2.19.1

---

Formula/stratus-red-team.rb

Brew formula update for stratus-red-team version v2.20.0

---

Formula/stratus-red-team.rb

Brew formula update for stratus-red-team version v2.21.0

---

Formula/stratus-red-team.rb

Brew formula update for stratus-red-team version v2.23.0

---

docs/attack-techniques/entra-id/entra-id.persistence.hidden-au.md
docs/attack-techniques/entra-id/entra-id.persistence.restricted-au.md
v2/internal/attacktechniques/entra-id/persistence/hidden-au/main.go
v2/internal/attacktechniques/entra-id/persistence/restricted-au/main.go

Fix TODO and grammar in AU technique documentation.
I left a "TODO" in technique docs back in November, this PR addresses that by fully explaining the Hidden Membership technique and fixing up Restricted AU grammar a bit.
N/A

Update AU Documentation
