internal/attacktechniques/aws/discovery/ec2-get-user-data/main.go, internal/attacktechniques/aws/discovery/ec2-get-user-data/main.tf, internal/attacktechniques/main.go, internal/utils/functions.go
Implements the technique described in #62.
aws.exfiltration.ec2-download-user-data
Runs ec2:DescribeInstanceAttribute on several instances (non-existent, and unauthorized). This simulates an attacker attempting to retrieve Instance User Data that may include installation scripts and hard-coded secrets for deployment.
References:
- https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html
- https://hackingthe.cloud/aws/general-knowledge/introduction_user_data/
- https://github.com/RhinoSecurityLabs/pacu/blob/master/pacu/modules/ec2__download_userdata/main.py
I added a detection comment for https://github.com/DataDog/stratus-red-team/pull/81
=> New technique : aws.discovery.ec2-get-user-data

internal/attacktechniques/aws/discovery/ec2-get-user-data/main.go
Fixing this by deleting the indentation:
=> Quick fix detection doc for aws.discovery.ec2-get-user-data

internal/providers/aws.go, internal/providers/kubernetes.go, internal/providers/main.go
Use a custom user-agent when interacting with the Kubernetes API server
- Make Stratus Red Team requests more visible
Before:
After:
=> Customize K8s user-agent

docs/attack-techniques/kubernetes/index.md, docs/attack-techniques/kubernetes/k8s.persistence.create-admin-clusterrole.md, docs/attack-techniques/kubernetes/k8s.privilege-escalation.create-admin-clusterrole.md, docs/attack-techniques/kubernetes/k8s.privilege-escalation.privileged-pod.md, docs/attack-techniques/list.md, internal/attacktechniques/k8s/persistence/create-admin-clusterrole/main.go, internal/attacktechniques/k8s/privilege-escalation/create-admin-clusterrole/main.go, internal/attacktechniques/main.go
Introduce a new TTP
- Should this be privesc or persistence?
```
2022/02/07 23:28:36 Checking your authentication against Kubernetes
2022/02/07 23:28:36 Creating Cluster Role stratus-red-team-clusterrole
2022/02/07 23:28:36 Creating Service Account stratus-red-team-serviceaccount
2022/02/07 23:28:36 Creating Cluster Role Binding to map the service account to the cluster role
2022/02/07 23:28:36 Successfully generate service account token:
eyJhbGciO...
```
Decoding to:
=> New attack technique: Create ClusterAdmin role

internal/attacktechniques/aws/credential-access/ec2-steal-instance-credentials/main.tf, internal/attacktechniques/aws/discovery/ec2-enumerate-from-instance/main.tf, internal/attacktechniques/aws/execution/ec2-user-data/main.tf
* Bug fix
Terrform scripts for multiple techniques creates a static IP for ec2 instances using aws_network_interface. The interface is never attached to the ec2 instances, therefore instances are launched into the region's default VPC instead of one created with stratus.
This was discovered because AWS account was setup using recommended control [[EC2.2] The VPC default security group should not allow inbound and outbound traffic](https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html#fsbp-ec2-2)
The PR fix attaches the network interfaces to the instances for each technique that were broken.
=> Network interfaces not attached to ec2 instances

docs/attack-techniques/kubernetes/index.md, docs/attack-techniques/kubernetes/k8s.credential-access.dump-secrets.md, docs/attack-techniques/kubernetes/k8s.privilege-escalation.nodes-proxy.md, docs/attack-techniques/list.md, internal/attacktechniques/k8s/privilege-escalation/nodes-proxy/main.go, internal/attacktechniques/k8s/privilege-escalation/nodes-proxy/main.tf, internal/attacktechniques/main.go
Tested on Minikube and EKS.
Sample output:
```
2022/03/04 11:12:20 Checking your authentication against kubernetes
2022/03/04 11:12:21 Warming up k8s.privilege-escalation.node-proxy
2022/03/04 11:12:21 Initializing Terraform to spin up technique prerequisites
2022/03/04 11:12:24 Applying Terraform to spin up technique prerequisites
2022/03/04 11:12:31 K8s service account with node/proxy permission is ready: stratus-red-team-node-proxy-sa in namespace stratus-red-team-rzaydove
2022/03/04 11:12:31 Retrieving service account token for service account stratus-red-team-node-proxy-sa
2022/03/04 11:12:31 Using worker node 'ip-192-168-34-255.eu-west-1.compute.internal' to proxy to the Kubelet API
2022/03/04 11:12:31 Performing request to …
```
=> New attack technique: K8s privilege escalation through nodes/proxy permissions

internal/attacktechniques/aws/exfiltration/ec2-share-ami/main.go, internal/attacktechniques/aws/exfiltration/ec2-share-ebs-snapshot/main.go, internal/utils/aws_utils.go, internal/utils/aws_utils_test.go
New output:
```
2022/03/30 18:48:19 Checking your authentication against AWS
2022/03/30 18:48:20 Warming up aws.exfiltration.ec2-share-ebs-snapshot
2022/03/30 18:48:20 Initializing Terraform to spin up technique prerequisites
2022/03/30 18:50:16 Applying Terraform to spin up technique prerequisites
2022/03/30 18:50:43 Snapshot snap-0f22b58c34517e0a7 of vol-0c8e25f1f6706e29b ready
2022/03/30 18:50:43 Sharing the volume snapshot snap-0f22b58c34517e0a7 with an external AWS account...
2022/03/30 18:50:45 Note: Stratus detonated the attack, but the sharing was unsuccessful. This is likely because EBS default encryption is enabled in the region. Nonetheless, it did simulate a plausible attacker action.
```
=> Exfiltration of EBS snapshots and AMIs: Handle error when EBS encryption by default is enabled (closes #109)

go.mod, go.sum, internal/providers/aws.go, internal/providers/kubernetes.go, internal/providers/main.go, pkg/stratus/runner/runner.go
This allows for correlating alerts in external tools (such as Datadog) with a specific detonation. Sample PoC ugly code for Datadog:
```go
// Note: Doesn't handle cases where 1 detonation triggers multiple signals
package main
import (
"bytes"
"context"
"encoding/json"
"fmt"
"github.com/DataDog/datadog-api-client-go/api/v2/datadog"
"github.com/datadog/stratus-red-team/pkg/stratus"
_ "github.com/datadog/stratus-red-team/pkg/stratus/loader" // Note: This import is needed
stratusrunner "github.com/datadog/stratus-red-team/pkg/stratus/runner"
"log"
"net/http"
"os"
"strconv"
"strings"
"time"
)
func detonate() string {
ttp := stratus.GetRegistry().GetAttackTechniqueByName("k8s.persistence.create-admin-clusterrole")
stratusRunner := stratusrunner.NewRunner(ttp, …
```
=> Inject a unique detonation ID in the user-agent of K8s and AWS requests

pkg/stratus/runner/terraform.go
**Context**: This unique user-agent is currently injected in the AWS / Azure / K8s SDK.
**This PR**: Adds the same user-agent for Terraform (warm-up). It allows to identify any alert / log event created by the warm-up process easily
=> Add execution UUID to Terraform user-agent

docs/attack-techniques/azure/azure.exfiltration.disk-export.md, docs/attack-techniques/azure/index.md, docs/attack-techniques/list.md, internal/attacktechniques/azure/exfiltration/disk-export/main.go, internal/attacktechniques/azure/exfiltration/disk-export/main.tf, internal/attacktechniques/main.go
Implement a new attack technique that exports a VM disk using a Shared Access Signature public URL.
Sample output:
```
$  stratus detonate azure.exfiltration.disk-export
2022/06/10 23:19:54 Checking your authentication against azure
2022/06/10 23:19:54 Warming up azure.exfiltration.disk-export
2022/06/10 23:19:54 Initializing Terraform to spin up technique prerequisites
2022/06/10 23:20:01 Applying Terraform to spin up technique prerequisites
2022/06/10 23:20:44 Disk stratus-red-team-disk ready in resource group rg-323a8o8x
2022/06/10 23:20:44 Creating Shared Access Secret (SAS) URL for disk stratus-red-team-disk
2022/06/10 23:20:49 Successfully generated SAS URL for disk at https://md-hdd-jmnwsmmwsnjt.z33.blob.storage.azure.net/jntpcvfgz5jc/abcd?sv=2018-03-28&sr=b&si=d11697d3-79cc-403a-97 …
```
=> New attack technique: Export Disk Through SAS URL

cmd/stratus/main.go, pkg/stratus/loader/main.go
When using the programmatic interface, the logging shouldn't be displayed to stdout to avoid polluting the output of the application using it.
Logging was exclusively designed for usage in CLI mode
=> Disable logging when using the programmatic interface (closes #126)

cmd/stratus/cleanup_cmd.go, cmd/stratus/detonate_cmd.go, cmd/stratus/revert_cmd.go, cmd/stratus/show_cmd.go, cmd/stratus/util.go, cmd/stratus/warmup_cmd.go, docs/user-guide/commands/autocompletion.md, docs/user-guide/commands/index.md, mkdocs.yml
* Enhancement:  Add dynamic command line completion for available techniques (see [link](https://github.com/spf13/cobra/blob/master/shell_completions.md#dynamic-completion-of-nouns))
Add to `cmd` where felt it makes (most) sense i.e cleanup, detonate, revert, show, warmup
* What inspired you to submit this pull request?
Easier / more convenient to use.
E.g. :
`stratus warmup aws.exec[tab][tab]`  --> will autocomplete to  `stratus warmup aws.execution.ec2-user-data`
or
`stratus warmup aws.persist[tab]` --> will autocomplete to  `stratus warmup aws.persistence.` with another `[tab]` possible option (=techniques) are listed
```sh
$ stratus warmup aws.persistence.[tab]
aws.persistence.iam-backdoor-role              aws.persistence.iam-create-admin-user
aws.persistence.lambda-backdoor-function …
```
=> Add dynamic autocomplete for techniques

docs/attack-techniques/GCP/gcp.persistence.create-admin-service-account.md, docs/attack-techniques/GCP/index.md, docs/attack-techniques/list.md, v2/internal/attacktechniques/gcp/persistence/create-admin-service-account/main.go, v2/internal/attacktechniques/gcp/persistence/create-admin-service-account/main.tf, v2/internal/attacktechniques/main.go, v2/internal/providers/gcp.go, v2/internal/utils/functions.go
New attack technique: create a GCP service account and assign it `roles/editor` at the project level
Step 1: Create a service account (easy)
Step 2: Assign the service account editor rights at the project level (harder).
There is no API available to assign permissions to a service account at the project level. Instead, `gcloud projects add-iam-policy-binding` works as follows:
1. Read the project's IAM policy through [getIamPolicy](https://cloud.google.com/resource-manager/reference/rest/v1/projects/getIamPolicy)
2. Add the right binding
* If a binding for the role already exists, add the service account to the list of members
* Otherwise, create a new binding
3. Update the project's IAM policy through [setIamPolicy](https://cloud.google.com/resource-manager/reference/rest/v1/projects/setI …
=> Create an admin service account

docs/attack-techniques/azure/azure.execution.vm-custom-script-extension.md, docs/attack-techniques/azure/azure.execution.vm-run-command.md, v2/internal/attacktechniques/azure/execution/vm-custom-script-extension/main.go, v2/internal/attacktechniques/azure/execution/vm-run-command/main.go
* Update documentation for Azure techniques to reference the recently released [Azure Threat Research Matrix](https://techcommunity.microsoft.com/t5/security-compliance-and-identity/introducing-the-azure-threat-research-matrix/ba-p/3584976). The original links were pointing to a draft version of the project.
* Dead links are bad.
* The ATRM is an excellent resource was already the intended reference for the techniques
=> Update Azure technique docs to link to Azure Threat Research Matrix

docs/attack-techniques/GCP/gcp.privilege-escalation.impersonate-service-accounts.md, docs/attack-techniques/GCP/index.md, docs/attack-techniques/list.md, v2/internal/attacktechniques/gcp/privilege-escalation/impersonate-service-accounts/main.go, v2/internal/attacktechniques/gcp/privilege-escalation/impersonate-service-accounts/main.tf, v2/internal/attacktechniques/main.go, v2/pkg/stratus/runner/runner.go
New attack technique to simulate a situation where an attacker attempts to impersonate several GCP service accounts, and successfully manages for one. (#152)
Output (warmup):
```
$ stratus warmup gcp.privilege-escalation.impersonate-service-accounts
2022/08/04 11:46:10 Checking your authentication against GCP
2022/08/04 11:46:10 Warming up gcp.privilege-escalation.impersonate-service-accounts
2022/08/04 11:46:10 Initializing Terraform to spin up technique prerequisites
2022/08/04 11:46:18 Applying Terraform to spin up technique prerequisites
2022/08/04 11:46:24 10 service accounts created and ready:
- stratus-red-team-m2062fam@datadog-sandbox.iam.gserviceaccount.com
- stratus-red-team-5l21ck9g@datadog-sandbox.iam.gserviceaccount.com
- …
```
=> New attack technique: GCP Service Accounts impersonation

docs/attack-techniques/kubernetes/index.md, docs/attack-techniques/kubernetes/k8s.persistence.create-client-certificate.md, docs/attack-techniques/list.md, v2/internal/attacktechniques/k8s/persistence/create-client-certificate/main.go, v2/internal/attacktechniques/main.go
Adds a new Attack technique which creates and approves a Kubernetes Client Certificate with a username of `system:kube-controller-manager` which is a standard high-privileged user account in Kubernetes.
As Kubernetes does not allow for certificate revocation, this is a good persistence technique for attackers who have gained access to Kubernetes clusters (similar to the Token Request API)
There's two motivations for this technique. First is the standard of ensuring that cluster auditing are picking this up correctly. The second is with managed Kubernetes testing implementations to see if this feature works. For example in EKS it is not documented clearly whether general CSR process works.
=> Add new attack technique for Kubernetes persistence

Makefile, docs/index.yaml, v2/pkg/stratus/attack_technique.go, v2/pkg/stratus/mitreattack/tactics.go, v2/pkg/stratus/platform.go, v2/tools/generate-docs.go, v2/tools/generate-techniques-documentation.go, v2/tools/generate-yaml.go, v2/tools/index.go
Enhancement: `make docs` now generates a `docs/index.yaml` file with all techniques serialised into it.
Motivation is described on #172 
N/A
`index.yaml` file contains all techniques grouped by MITRE tactic and platform. Some techniques are classified with in 2 or more tactics, when that happens, the technique is duplicated in the document.
=> Enables `make docs` to generate a yaml file with all techniques and their metadata. Fixes #172

v2/internal/attacktechniques/aws/exfiltration/rds-share-snapshot/main.tf, v2/pkg/stratus/runner/runner.go
* Bug fix
* Enhancement
* https://github.com/DataDog/stratus-red-team/issues/140
* https://github.com/DataDog/stratus-red-team/issues/141
Behavior when detonating `aws.exfiltration.rds-share-snapshot` prior to this change (with no default VPC or default subnets configured):
```
2022/12/06 12:46:58 Checking your authentication against AWS
2022/12/06 12:46:59 Warming up aws.exfiltration.rds-share-snapshot
2022/12/06 12:46:59 Applying Terraform to spin up technique prerequisites
2022/12/06 12:47:03 unable to run terraform apply on prerequisite: unable to apply Terraform: exit status 1
Error: Error creating DB Instance: InvalidSubnet: No default subnet detected in VPC. Please contact AWS Support to recreate default Subnets.
status code: 400, request id: ______
with aws_db_instance.default,
on …
```
=> Remove requirement for default VPC and default subnets from aws.exfiltration.rds-share-snapshot. Add output indicating if an attack technique is slow.

v2/internal/attacktechniques/azure/execution/vm-custom-script-extension/main.tf, v2/internal/attacktechniques/azure/execution/vm-run-command/main.tf
=> Fix resource name lengths in Azure attack techniques (closes #301)

v2/internal/attacktechniques/gcp/privilege-escalation/impersonate-service-accounts/main.go
- Fix GCP attack technique failing to impersonate service accounts (closes #299)
- Adapt GCP attack technique error message
- Update GCP docs quote
=> Fix broken GCP technique

v2/pkg/stratus/runner/runner.go, v2/pkg/stratus/runner/runner_test.go
=> Cleanup AWS resources in case of warm up error

.goreleaser.yaml, docs/user-guide/commands/autocompletion.md
* Enhancement! This will automatically install shell completions, generated by the installed `stratus` binary in their proper locations for users of the Homebrew tap. This method from Homebrew supports bash, fish, and zsh. _Sorry PowerShellers._
I just wanted to have the formula install completions automatically in the most correct manner possible.
* [Homebrew formula documentation](https://rubydoc.brew.sh/Formula#generate_completions_from_executable-instance_method) for `generate_completions_from_executable` method
* [Goreleaser brew documentation](https://goreleaser.com/customization/homebrew/) for custom install definition
I've never actually used Goreleaser before, but I think I got this right! I tested as much as I could locally, but I have *not* actually tested the creation of the …
=> Goreleaser/Homebrew: Install shell completions

v2/go.mod, v2/go.sum, v2/internal/attacktechniques/aws/credential-access/ec2-get-password-data/main.go, v2/internal/attacktechniques/aws/defense-evasion/organizations-leave/main.go, v2/internal/attacktechniques/aws/discovery/ec2-get-user-data/main.go, v2/internal/attacktechniques/aws/execution/ec2-launch-unusual-instances/main.go, v2/internal/utils/aws_utils.go
Several attack techniques start by creating an IAM role and assuming it. Unfortunately, AWS IAM is _eventually consistent_, meaning that a role may not be assumable right away. It can take anywhere from a few seconds (usually) to a minute (rare) for changes to propagate.
This was causing #353.
This PR implements a retry mechanism with exponential backoff. It will try to assume the role right away, then wait up to 10 seconds until it succeeds (1 minute most)
=> Implement retry mechanism when creating and assuming an IAM role ^

v2/internal/attacktechniques/aws/persistence/lambda-backdoor-function/main.tf
closes #359 
Thanks @dayspringjohnson for the report
=> Fix aws.persistence.lambda-backdoor-function failing due to unsupported NodeJS Lambda version (closes #359)

examples/custom/prerequisites.tf, v2/internal/attacktechniques/aws/credential-access/ec2-get-password-data/main.tf, v2/internal/attacktechniques/aws/credential-access/ec2-steal-instance-credentials/main.tf, v2/internal/attacktechniques/aws/credential-access/secretsmanager-retrieve-secrets/main.tf, v2/internal/attacktechniques/aws/credential-access/ssm-retrieve-securestring-parameters/main.tf, v2/internal/attacktechniques/aws/defense-evasion/cloudtrail-delete/main.tf, v2/internal/attacktechniques/aws/defense-evasion/cloudtrail-event-selectors/main.tf, v2/internal/attacktechniques/aws/defense-evasion/cloudtrail-lifecycle-rule/main.tf, v2/internal/attacktechniques/aws/defense-evasion/cloudtrail-stop/main.tf, v2/internal/attacktechniques/aws/defense-evasion/organizations-leave/main.tf, v2/internal/attacktechniques/aws/defense-evasion/vpc-remove-flow-logs/main.tf, v2/internal/attacktechniques/aws/discovery/ec2-enumerate-from-instance/main.tf, v2/internal/attacktechniques/aws/discovery/ec2-get-user-data/main.tf, v2/internal/attacktechniques/aws/execution/ec2-launch-unusual-instances/main.tf, v2/internal/attacktechniques/aws/execution/ec2-user-data/main.tf, v2/internal/attacktechniques/aws/exfiltration/ec2-security-group-open-port-22-ingress/main.tf, v2/internal/attacktechniques/aws/exfiltration/ec2-share-ami/main.tf, v2/internal/attacktechniques/aws/exfiltration/ec2-share-ebs-snapshot/main.tf, v2/internal/attacktechniques/aws/exfiltration/rds-share-snapshot/main.tf, v2/internal/attacktechniques/aws/exfiltration/s3-backdoor-bucket-policy/main.tf, v2/internal/attacktechniques/aws/initial-access/console-login-without-mfa/main.tf, v2/internal/attacktechniques/aws/persistence/iam-backdoor-role/main.tf, v2/internal/attacktechniques/aws/persistence/iam-backdoor-user/main.tf, v2/internal/attacktechniques/aws/persistence/iam-create-user-login-profile/main.tf, v2/internal/attacktechniques/aws/persistence/lambda-backdoor-function/main.tf, v2/internal/attacktechniques/aws/persistence/lambda-overwrite-code/main.tf, v2/internal/attacktechniques/aws/persistence/rolesanywhere-create-trust-anchor/main.tf
closes https://github.com/DataDog/stratus-red-team/issues/367.
TL;DR: AWS Providers initialised with `skip_metadata_api_check = true` prevent Stratus techniques executing within AWS contexts from discovering instance profile credentials. This change will allow the terraform provider to use the instance-profile assigned to the EC2 within which Stratus is running as it won't skip checking the Instance Metadata for those credentials.
=> Remove `skip_metadata_api_check = true` from TF AWS Provider

v2/internal/attacktechniques/aws/execution/ec2-launch-unusual-instances/main.go
closes #387
We were not catching the right error code (seems that it can sometimes be UnauthorizedOperation instead of AccessDenied)
=> [AWS] Catch the appropriate error in aws.execution.ec2-launch-unusual-instances (closes #387)

v2/internal/attacktechniques/gcp/exfiltration/share-compute-disk/main.go, v2/internal/attacktechniques/gcp/persistence/backdoor-service-account-policy/main.go, v2/internal/attacktechniques/gcp/persistence/invite-external-user/main.go, v2/internal/utils/gcp/gcp_utils.go
This adds the `STRATUS_RED_TEAM_ATTACKER_EMAIL` env variable to change the attacker email that is used in the IAM policy for `gcp.exfiltration.share-compute-disk` 
This addresses #385 and allows user of the technique to use their own external user.
=> Add STRATUS_RED_TEAM_ATTACKER_EMAIL env to gcp.exfiltration.share-compute-disk

docs/attack-techniques/AWS/aws.persistence.iam-backdoor-user.md, docs/attack-techniques/AWS/aws.persistence.iam-create-admin-user.md, docs/attack-techniques/AWS/aws.persistence.iam-create-user-login-profile.md, docs/attack-techniques/AWS/aws.persistence.lambda-layer-extension.md, docs/attack-techniques/AWS/aws.persistence.lambda-overwrite-code.md, docs/attack-techniques/AWS/index.md, docs/attack-techniques/GCP/gcp.persistence.create-admin-service-account.md, docs/attack-techniques/list.md, docs/index.yaml, v2/internal/attacktechniques/aws/persistence/lambda-layer-extension/main.go, v2/internal/attacktechniques/aws/persistence/lambda-layer-extension/main.tf, v2/internal/attacktechniques/main.go
* New attack technique
2 weeks ago, AWS published an [article ](https://aws.amazon.com/es/blogs/compute/enhancing-runtime-security-and-governance-with-the-aws-lambda-runtime-api-proxy-extension/) about how to enhance runtime security using lambda extensions.
An attacker can abuse this same technique to gain persistence. Last year, ClearVector described in detail how to perform this attack in [this article](https://www.clearvector.com/blog/lambda-spy/).
Because a Lambda can use layers from other accounts, an attacker with access to a lambda can add a new layer to compromise the lambda without changing the code. 
The extension created by the terraform is not malicious. It is the one from [this](https://github.com/aws-samples/aws-lambda-extensions/tree/main/python-example-extension) example. …
=> New attack technique: Persistence AWS Lambda Layer Extension

v2/internal/attacktechniques/k8s/credential-access/steal-serviceaccount-token/main.tf, v2/internal/attacktechniques/k8s/privilege-escalation/nodes-proxy/main.tf
=> Bump Terraform Kubernetes provider to support recent K8s versiont that don't create service account token secrets by default

v2/internal/attacktechniques/aws/defense-evasion/organizations-leave/main.tf
* Bug fix: Adds the `sts:TagSession` permission to the Trust Relationship config for the role used to detonate `aws.defense-evasion.organizations-leave`. Without this permission, Stratus returns 403 Forbidden errors from AWS due to insufficient permissions. See issue below for more details
Issue raised here: https://github.com/DataDog/stratus-red-team/issues/462
=> Add sts:TagSession permission to Stratus role

docs/attack-techniques/AWS/aws.execution.ssm-send-command.md, docs/attack-techniques/AWS/index.md, docs/attack-techniques/list.md, docs/index.yaml, v2/internal/attacktechniques/aws/execution/ssm-send-command/main.go, v2/internal/attacktechniques/aws/execution/ssm-send-command/main.tf, v2/internal/attacktechniques/main.go
see #480 
Pretty similar to https://stratus-red-team.cloud/attack-techniques/AWS/aws.execution.ssm-start-session/ recently implemented
=> New technique: Usage of ssm:SendCommand on multiple instances

v2/internal/providers/aws.go, v2/pkg/stratus/providers.go
(closes #506)
new output:
```
2024/04/04 12:17:34 Checking your authentication against AWS
2024/04/04 12:17:34 you are not authenticated against AWS, *or* you have not set your region.
Troubleshooting:
1. Are you authenticated against AWS?
2. Do you have a region or default region set, in your AWS configuration file or in your environment? (AWS_REGION or AWS_DEFAULT_REGION)
```
=> Implement better error message when the AWS region or AWS default region is missing 

docs/attack-techniques/AWS/aws.defense-evasion.dns-delete-logs.md, v2/internal/attacktechniques/aws/defense-evasion/dns-delete-logs/main.go
Corrected the AWS CloudTrail Event name for detection
- Correct the KB for aws.defense-evasion.dns-delete-logs to show the current CloudTrail event name
- When detonating this attack, `DeleteQueryLoggingConfig` does not show up in CloudTrail logs. Instead, the event `DeleteResolverQueryLogConfig` shows.
=> Update aws.defense-evasion.dns-delete-logs.md with current CloudTrail event name

README.md
Document how to install stratus-red-team using [asdf](https://asdf-vm.com/).
I have also slightly changed how installation methods are listed for clarity. 
Using [asdf](https://asdf-vm.com/) and the [plugin I wrote for stratus-red-team](https://github.com/vthiery/asdf-stratus-red-team) is a convenient way to use / test different versions of stratus-red-team.
NA
=> docs: add asdf as way to install

docs/attack-techniques/AWS/aws.execution.ec2-user-data.md, docs/attack-techniques/AWS/aws.execution.ssm-send-command.md, docs/attack-techniques/AWS/aws.execution.ssm-start-session.md, docs/attack-techniques/AWS/aws.lateral-movement.ec2-instance-connect.md, docs/attack-techniques/azure/azure.execution.vm-custom-script-extension.md, docs/attack-techniques/azure/azure.execution.vm-run-command.md
Adds references to https://unit42.paloaltonetworks.com/cloud-virtual-machine-attack-vectors/ for applicable techniques mentioned in this writeup:
Cloud | Writeup Technique | Writeup Name | Stratus Technique
-- | -- | -- | --
AWS | Direct Code Execution | Use SSM Run Command to Execute Code | /AWS/aws.execution.ssm-send-command.md
AWS | SSH Key Push | Use EC2 Instance Connect to Push SSH Keys | /AWS/aws.lateral-movement.ec2-instance-connect.md
AWS | Startup Script Manipulation | Modify Startup Scripts in User Data | /AWS/aws.execution.ec2-user-data.md
AWS | SSH Over Middleware | Use SSM Session Manager to Log into a VM | /AWS/aws.execution.ssm-start-session.md
Azure | Direct Code Execution | Use Virtual Machine Run Command to Execute Code | /azure/azure.execution.vm-run-command.md
Azure | …
=> Updating technique references for Unit42 VM Attack Path article.

v2/pkg/stratus/runner/runner.go, v2/pkg/stratus/runner/runner_test.go
Used for mocking in projects that use Stratus Red Team programmatically (and also a good practice).
Should be retro-compatible
=> Stratus Red Team runner: expose interface instead of implementation

docs/attack-techniques/AWS/aws.persistence.sts-federation-token.md, docs/attack-techniques/AWS/index.md, docs/attack-techniques/list.md, docs/detonation-logs/aws.persistence.sts-federation-token.json, docs/index.yaml, v2/internal/attacktechniques/aws/persistence/sts-federation-token/main.go, v2/internal/attacktechniques/aws/persistence/sts-federation-token/main.tf, v2/internal/attacktechniques/main.go
* New attack technique
I saw that this was an open and prioritized issue: https://github.com/DataDog/stratus-red-team/issues/313
The current implementation creates an IAM user and a pair of access keys, one enabled and the other disabled. I use the enabled credentials to call the GetFederationToken API. This is not done directly from the credentials used in the Stratus Red Team session because GetFederationToken generates temporary security credentials for a user. If you're using a role to execute Stratus Red Team, this approach likely won't work. Instead, using the credentials of the IAM user created during the warmup phase allows us to successfully reproduce the GetFederationToken step.
Afterward, I only call the sts:GetCallerIdentity API to verify that the session works. I am not …
=> New attack technique: Persistence through federation

docs/contributing.md
Update link in `contributing.md` to point to the correct label for new issues, `kind/new-technique`. Currently, this link points to `new-technique`, which leads to an empty page:
Fixing this after a user noticed this & pointed it out to me.
N/A, change in link filter.
=> Update new issue label link in contributing.md

v2/internal/utils/aws_utils.go
```
stratus detonate aws.credential-access.ec2-steal-instance-credentials 
```
before:
```
2024/11/19 16:59:06 Waiting for instancei-0<snipped> to show up in AWS SSM
```
after:
```
2024/11/19 16:59:06 Waiting for instance i-0<snipped> to show up in AWS SSM
```
Just adding a blank space to make the log more readable.
=> [Enhancement] Add blank space before instance-id in log.Println

v2/internal/attacktechniques/aws/credential-access/ec2-steal-instance-credentials/main.tf, v2/internal/attacktechniques/aws/discovery/ec2-enumerate-from-instance/main.tf, v2/internal/attacktechniques/aws/execution/ec2-launch-unusual-instances/main.tf, v2/internal/attacktechniques/aws/execution/ec2-user-data/main.tf, v2/internal/attacktechniques/aws/execution/ssm-send-command/main.tf, v2/internal/attacktechniques/aws/execution/ssm-start-session/main.tf, v2/internal/attacktechniques/aws/exfiltration/rds-share-snapshot/main.tf, v2/internal/attacktechniques/aws/lateral-movement/ec2-send-serial-console-send-ssh-public-key/main.tf, v2/internal/attacktechniques/aws/lateral-movement/ec2-send-ssh-public-key/main.tf
The fix in #629 incorrectly changed version constraints for the Terraform AWS VPC module, while it was meant to be changed only for the Terraform AWS provider
As reported in https://github.com/DataDog/stratus-red-team/issues/626#issuecomment-2681693462
=> Fix incorrect AWS VPC module version (#626)
